spring.application.name=demo


# Ma'lumotlar bazasi ulanishi
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=sizning_parolingiz

# Hibernate sozlamalari
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
# Serverning javob berish vaqtini cheklamang (millisekundda)
server.netty.connection-timeout=20000

# SQL so'rovlarni konsolda ko'rish uchun

logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
